Fixing boundaries
djmattyg007/official-library-php-email-parser pull request #5
Opened 2017-02-16 14:42 UTC by MartijnBraam

This fixes the regex that checks for boundaries (The end of line detection was wrong)
It also makes the regex strip the quotes if they exist and made the regex more strict (and no longer contains unbound searches)

This pullrequest also contains the chaines for #4

2017-02-18 01:38 UTC, djmattyg007 requested changes
Thank you so much for putting together PHPUnit test cases. I'm incredibly thankful for your contribution. There's a few things that need updating, but they're mostly small things. All of the logic changes look fine to me.

2017-02-18 01:38 UTC, djmattyg007 commented on PlancakeEmailParser.php
> +        preg_match_all('/boundary=(?:|")([a-zA-Z0-9\(\)_\/+-]+)(?:|")(?:$|;)/mi', $this->emailRawContent, $matches);
Could you please outline exactly what was wrong with the previous regex? This definitely looks more comprehensive than the previous one and more correct, but I'd appreciate it if you could outline some cases where the old regex didn't work but the new one does.

Also, can you please update the comment on line 414 to include the detail in the comment that was on line 419 but has been removed by your changes.

2017-02-18 01:38 UTC, djmattyg007 commented on tests/PlancakeEmailParserTest.php
> +declare(strict_types = 1);
As much as I love PHP 7 and its strict typing, technically this library still supports PHP5. I'm fine with dropping support for anything prior to PHP 5.6, but ideally I still need to be able to run the tests on PHP 5.6 for the foreseeable future. Could you therefore please remove this.

2017-02-18 01:38 UTC, djmattyg007 commented on tests/PlancakeEmailParserTest.php
> +    foreach (glob(__DIR__ . '/emails/*.txt') as $testFile) {
Brace placement and indentation needs to follow the existing conventions of this codebase (which generally follow PSR-2).

2017-02-18 01:38 UTC, djmattyg007 commented on tests/PlancakeEmailParserTest.php
> +      $answers = \Symfony\Component\Yaml\Yaml::parse(
Add a `use` statement for `Symfony\Component\Yaml\Yaml` at the top of the file.

2017-02-18 01:38 UTC, djmattyg007 commented on tests/bootstrap.php
> +require_once(__DIR__ . '/../vendor/autoload.php');
I prefer this style of writing paths:

    require_once(dirname(__DIR__) . '/vendor/autoload.php');

2017-02-18 01:38 UTC, djmattyg007 commented on tests/emails/0.yml
> +            Pawel
Can you please ensure that all of these files have a trailing newline.
See here for context: https://unix.stackexchange.com/questions/18743/whats-the-point-in-adding-a-new-line-to-the-end-of-a-file

2017-02-18 01:39 UTC, djmattyg007 commented
Also, could you please close the other PR in favour of this one.

2017-02-18 12:48 UTC, MartijnBraam commented on PlancakeEmailParser.php
> +        preg_match_all('/boundary=(?:|")([a-zA-Z0-9\(\)_\/+-]+)(?:|")(?:$|;)/mi', $this->emailRawContent, $matches);
The [;$] part didn't seem to work on any of the test cases (at least in my php7 installation)

2017-02-18 12:49 UTC, MartijnBraam commented on tests/PlancakeEmailParserTest.php
> +declare(strict_types = 1);
Hmm yes, I copied that straight from the phpunit docs without thinking.

2017-02-18 14:13 UTC, MartijnBraam commented on tests/emails/0.yml
> +            Pawel
I didn't give them newlines since that line is included in the multiline field, making the test fail.

Fixed it with another syntax in yaml.

2017-02-18 14:14 UTC, MartijnBraam commented
I changed all the points in your review.

2017-02-22 21:55 UTC, djmattyg007 approved these changes

2017-02-22 21:56 UTC, merged

2017-02-22 21:57 UTC, djmattyg007 commented
I've merged all of your changes. Thanks for your contribution! I'll be issuing a new release within the next 24 hours with your improvements.

2017-02-23 21:55 UTC, djmattyg007 commented
I've just released v4.0.0 https://github.com/djmattyg007/official-library-php-email-parser/releases/tag/4.0.0

Two of the subject-parsing test cases were failing on my machine, as I have the IMAP PHP extension installed and enabled. It turned out that not using the IMAP extension produced incorrect results for any encoded non-ASCII text. As a result, I've made the decision to require the IMAP extension to ensure correct, consistent results across all environments. I apologise if this requires you to make changes to your runtime environments, but I figured it was best not to persist with a solution that could produce two different results in two different environments due to what amounts to a misconfiguration.

2017-02-24 13:26 UTC, MartijnBraam commented
I chosen this class because I couldn't install the imap extension. Wouldn't it be better to just fix the encoding issue?

2017-02-24 21:38 UTC, djmattyg007 commented
The issue isn't with the input (which is perfecrly valid). The `iconv_mime_decode` function quite simply produces incorrect results for text with various diacritics, and my preference is that this library cannot produce incorrect results under any circumstances.

I've opened an issue at the Symfony Polyfill repository to see if anyone is aware of a proper polyfill: https://github.com/symfony/polyfill/issues/83

A possible interim solution may be to allow forcing the undesirable behaviour by making the user set a variable on the object. What sort of override would suit you best?

2017-02-24 22:08 UTC, djmattyg007 commented
It looks like an override is unnecessary. The `mb_decode_mimeheader()` function works perfectly as a replacement, so I'll be pushing a new version shortly that uses that instead.

2017-02-24 23:20 UTC, djmattyg007 commented
I've just pushed a new version that removes the dependency on the IMAP PHP extension https://github.com/djmattyg007/official-library-php-email-parser/releases/tag/5.0.0

Given you started off by using PHP7 syntax in the PHPUnit test, I hope the fact that I've dropped support for PHP <= 5.5 won't be a problem.

I've also set up CI on Travis: https://travis-ci.org/djmattyg007/official-library-php-email-parser